//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace xstudio.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("xstudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 function js_beautify(js_source_text, options) {
        ///
        ///    var input, output, token_text, last_type, last_text, last_last_text, last_word, flags, flag_store, indent_string;
        ///    var whitespace, wordchar, punct, parser_pos, line_starters, digits;
        ///    var prefix, token_type, do_block_just_closed;
        ///    var wanted_newline, just_added_newline, n_newlines;
        ///
        ///
        ///    // Some interpreters have unexpected results with foo = baz || bar;
        ///    options = options ? options : {};
        ///    var opt_braces_on_own_line = options.brac [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JSBeautify {
            get {
                return ResourceManager.GetString("JSBeautify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var log = android.util.Log;
        ///var ref = org.joor.Reflect;
        ///
        ///var main = function(lpparm, ctx, param) {
        ///    try {
        ///        var clazz = ref.on(param).type();
        ///        return toJson(clazz);
        ///    } catch (e) {
        ///		var clazz = ref.on(param, ctx.getClassLoader()).type();
        ///        return toJson(clazz);
        ///    }
        ///}
        ///
        ///var toJson = function(clazz) {
        ///    var fields = clazz.getDeclaredFields();
        ///    var methods = clazz.getDeclaredMethods();
        ///    var constructors = clazz.getDeclaredConstructors();
        ///
        ///    var array = new  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JSReflect {
            get {
                return ResourceManager.GetString("JSReflect", resourceCulture);
            }
        }
    }
}
